# https://github.com/daviddarnes/alembic#configuration

# Build settings
markdown: kramdown
theme: alembic-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: /posts/:num/
# paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: l2fprod # jekyll-seo-tag > Owners twitter username
author: l2fprod # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Frederic Lavigne # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/l2fprod
    - https://www.linkedin.com/in/fredlavigne
    - https://github.com/l2fprod

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      posts
    feature_image: "//fredericlavigne.com/images/hero.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "fred's blog" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
description: "this is Frederic Lavigne's blog" # Site description and default description, also used in jekyll-seo-tag
url: "https://blog.fredericlavigne.com" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/l2fprod/blog.fredericlavigne.com"
email: "find-me-on@twitter.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/assets/favicon.ico"
# Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Blog: /
  Categories: /categories/
  Search: /search/

# navigation_footer:
  # Created by David Darnes: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/l2fprod
  LinkedIn: https://www.linkedin.com/in/fredlavigne
  GitHub: https://github.com/l2fprod
  link: https://fredericlavigne.com
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
